### PR TITLE
Update Settings.view.dart

### PR DESCRIPTION
**Pull request by Hchoudhry15**
Added a toggle switch to know when volunteers are active to help

### CODE REVIEW

**Review by JohnRamberger — APPROVED** [review]

**Review by kozyjamal — COMMENTED** [review]
font size needs to be increase a little, otherwise good

**Comment by acoustic-git-tar** [comment]
looks good to me

**Review by acoustic-git-tar — COMMENTED** [review]
👍

**Review by medhanak — COMMENTED** [review]
great work!

**Pull request merged**
